/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-06-04 07:05:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.role;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/H:/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Atcrowdfunding-main/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1588300696268L));
    _jspx_dependants.put("/WEB-INF/jsp/common/top.jsp", Long.valueOf(1590029111820L));
    _jspx_dependants.put("jar:file:/H:/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Atcrowdfunding-main/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/jsp/common/menu.jsp", Long.valueOf(1590461638677L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".tree li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tbody tr:nth-child(odd) {\r\n");
      out.write("\tbackground: #F4F4F4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tbody td:nth-child(even) {\r\n");
      out.write("\tcolor: #C00;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <div><a class=\"navbar-brand\" style=\"font-size:32px;\" href=\"user.html\">众筹平台 - 用户维护</a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          \r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("   <li style=\"padding-top:8px;\">\r\n");
      out.write("\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"btn btn-default btn-success dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t  </button>\r\n");
      out.write("\t\t\t\t\t  <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i> 个人设置</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i> 消息</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout.htm\"><i class=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("\t\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("            <li style=\"margin-left:10px;padding-top:8px;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-danger\">\r\n");
      out.write("\t\t\t\t  <span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t     <form class=\"navbar-form navbar-right\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>");
      out.write("\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t\t\t\t<div class=\"tree\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul style=\"padding-left:0px;\" class=\"list-group\">\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("</ul> \r\n");
      out.write(" \r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-th\"></i> 数据列表\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-inline\" name=\"form\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group has-feedback\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-addon\">查询条件</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"queryText\" class=\"form-control has-success\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"请输入查询条件\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-warning\" onclick=\"queryRole()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-search\"></i> 查询\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"batchDelete\" type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right; margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-remove\"></i> 删除\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right;\" onclick=\"window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/role/add.htm'\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-plus\"></i> 新增\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<hr style=\"clear: both;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table  table-bordered\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"30\">#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"30\"><input type=\"checkbox\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"100\">操作</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- <ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"Pagination\" class=\"pagination\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/script/docs.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery/layer/layer.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("            $(function () {\r\n");
      out.write("\t\t\t    $(\".list-group-item\").click(function(){\r\n");
      out.write("\t\t\t\t    if ( $(this).find(\"ul\") ) {\r\n");
      out.write("\t\t\t\t\t\t$(this).toggleClass(\"tree-closed\");\r\n");
      out.write("\t\t\t\t\t\tif ( $(this).hasClass(\"tree-closed\") ) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).show(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t   \t\t queryPage(1);\r\n");
      out.write("\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    showMenu();\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            function changePageno( pageno ) {\r\n");
      out.write("            \tqueryPage(pageno);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            //使用Ajax异步查询数据\r\n");
      out.write("            function queryPage( pageno ){\r\n");
      out.write("            \tvar dataObj = {\r\n");
      out.write("        \t\t\t\"pageno\" : pageno ,   //pageno 是属性名称,是否增加双引号无所谓\r\n");
      out.write("        \t\t\t\"pagesize\" : 3\r\n");
      out.write("        \t\t};\r\n");
      out.write("            \tif(condition){\r\n");
      out.write("            \t\tdataObj.queryText = $(\"#queryText\").val(); //增加模糊查询条件\r\n");
      out.write("            \t}\r\n");
      out.write("            \t\r\n");
      out.write("            \tvar loadingIndex = -1 ;\r\n");
      out.write("            \t$.ajax({\r\n");
      out.write("            \t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/role/pageQuery.do\",\r\n");
      out.write("            \t\ttype : \"post\",\r\n");
      out.write("            \t\tdata : dataObj,\r\n");
      out.write("            \t\tbeforeSend : function(){\r\n");
      out.write("            \t\t\tloadingIndex = layer.msg('数据查询中', {icon: 6});\r\n");
      out.write("            \t\t\treturn true ;\r\n");
      out.write("            \t\t},\r\n");
      out.write("            \t\tsuccess : function(result){\r\n");
      out.write("            \t\t\t//显示结果\r\n");
      out.write("            \t\t\tlayer.close(loadingIndex);\r\n");
      out.write("            \t\t\tif(result.success){\r\n");
      out.write("            \t\t\t\t//循环遍历,显示数据\r\n");
      out.write("            \t\t\t\tvar pageObj = result.page;\r\n");
      out.write("            \t\t\t\tvar roleList = pageObj.datas ;\r\n");
      out.write("            \t\t\t\tvar content = \"\";\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t$.each(roleList,function(i,n){\r\n");
      out.write("            \t\t\t\t\t\r\n");
      out.write("            \t\t\t\t\tcontent+=\"<tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t<td>\"+(i+1)+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t<td><input type='checkbox' value='\"+n.id+\"'></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t<td>\"+n.name+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t<td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t<button type='button' onclick='window.location.href=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/role/assignPermission.htm?roleid=\"+n.id+\"\\\"' class='btn btn-success btn-xs'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t\t<i class=' glyphicon glyphicon-check'></i>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t<button type='button' onclick='window.location.href=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/role/edit.htm?pageno=\"+pageObj.pageno+\"&id=\"+n.id+\"\\\"' class='btn btn-primary btn-xs'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t\t<i class=' glyphicon glyphicon-pencil'></i>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t<button type='button' class='btn btn-danger btn-xs' onclick='deleteRole(\"+n.id+\",\\\"\"+n.name+\"\\\")'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t\t<i class=' glyphicon glyphicon-remove'></i>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t\t</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"\t</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent+=\"</tr>\";\r\n");
      out.write("            \t\t\t\t\t//$(\"tbody\").append(content);\r\n");
      out.write("            \t\t\t\t\t$(\"tbody\").html(content);\r\n");
      out.write("            \t\t\t\t});\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t//拼接导航条\r\n");
      out.write("            \t\t\t\t var pageContent = \"\";\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tif(pageObj.pageno!=1){\r\n");
      out.write("            \t\t\t\t\tpageContent += '<li><a href=\"#\" onclick=\"changePageno('+(pageObj.pageno-1)+')\">上一页</a></li>';\r\n");
      out.write("            \t\t\t\t}\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tfor(var i=1 ; i<=pageObj.totalno ; i++){\r\n");
      out.write("            \t\t\t\t\tif(i==pageObj.pageno){\r\n");
      out.write("\t            \t\t\t\t\tpageContent += '<li class=\"active\"><a href=\"#\" onclick=\"changePageno('+i+')\">'+i+'</a></li>';\r\n");
      out.write("            \t\t\t\t\t\t\r\n");
      out.write("            \t\t\t\t\t}else{\r\n");
      out.write("\t            \t\t\t\t\tpageContent += '<li><a href=\"#\" onclick=\"changePageno('+i+')\">'+i+'</a></li>';\r\n");
      out.write("            \t\t\t\t\t\t\r\n");
      out.write("            \t\t\t\t\t}\r\n");
      out.write("            \t\t\t\t}\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tif(pageObj.pageno!=pageObj.totalno){\r\n");
      out.write("            \t\t\t\t\tpageContent += '<li><a href=\"#\" onclick=\"changePageno('+(pageObj.pageno+1)+')\">下一页</a></li>';\r\n");
      out.write("            \t\t\t\t}\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t$(\".pagination\").html(pageContent);\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\t// 创建分页\r\n");
      out.write("           \t\t  \t\t /* \tvar num_entries = pageObj.totalsize ;\r\n");
      out.write("            \t\t\t\t$(\"#Pagination\").pagination(num_entries, {\r\n");
      out.write("            \t\t\t\t\tnum_edge_entries: 2, //边缘页数\r\n");
      out.write("            \t\t\t\t\tnum_display_entries: 2, //主体页数\r\n");
      out.write("            \t\t\t\t\tcallback: queryPage, //查询当前页的数据.\r\n");
      out.write("            \t\t\t\t\titems_per_page:pageObj.pagesize, //每页显示1项\r\n");
      out.write("            \t\t\t\t\t current_page:(pageObj.pageno-1), //当前页,索引从0开始\r\n");
      out.write("            \t\t\t\t\tprev_text:\"上一页\",\r\n");
      out.write("            \t\t\t\t\tnext_text:\"下一页\"\r\n");
      out.write("            \t\t\t\t});  */\r\n");
      out.write("            \t\t\t}else{\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tlayer.msg(\"角色分页查询数据失败\", {time:1000, icon:5, shift:6});\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t}\r\n");
      out.write("            \t\t},\r\n");
      out.write("            \t\terror : function(){\r\n");
      out.write("            \t\t\tlayer.msg(\"角色分页查询数据错误\", {time:1000, icon:5, shift:6});\r\n");
      out.write("            \t\t}\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t});\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            var condition = false ;\r\n");
      out.write("            //条件查询\r\n");
      out.write("            function queryRole(){\r\n");
      out.write("            \tvar queryText = $(\"#queryText\");\r\n");
      out.write("            \t\r\n");
      out.write("            \tif(queryText.val()==\"\"){\r\n");
      out.write("            \t\tlayer.msg(\"查询条件不能为空\", {time:1000, icon:5, shift:6}, function(){\r\n");
      out.write("            \t\t\tqueryText.focus();\r\n");
      out.write("            \t\t});\r\n");
      out.write("            \t\treturn ;\r\n");
      out.write("            \t}\r\n");
      out.write("            \tcondition = true ;\r\n");
      out.write("            \tqueryPage(1);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            function deleteRole(uid,name){\r\n");
      out.write("            \t\r\n");
      out.write("    \t\t\tlayer.confirm(\"是否要删除角色?\",  {icon: 3, title:'提示'}, function(cindex){\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t$.ajax({\r\n");
      out.write("    \t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/role/delete.do\",\r\n");
      out.write("    \t\t\t\t\ttype : \"POST\",\r\n");
      out.write("    \t\t\t\t\tdata : {uid:uid},\r\n");
      out.write("    \t\t\t\t\tsuccess : function(result){\r\n");
      out.write("    \t\t\t\t\t\tif(result.success){\r\n");
      out.write("    \t\t\t\t\t\t\tlayer.msg(\"删除\"+name+\"角色成功!\", {time:1000, icon:6}, function(){\r\n");
      out.write("    \t\t\t\t\t\t\t\tqueryPage(1);\r\n");
      out.write("    \t\t\t\t\t\t\t});\r\n");
      out.write("    \t\t\t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t\t\tlayer.msg(\"删除\"+name+\"角色失败!\", {time:1000, icon:5, shift:6});\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t});\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t    layer.close(cindex);\r\n");
      out.write("    \t\t\t}, function(cindex){    \t\t\t\t\r\n");
      out.write("    \t\t\t    layer.close(cindex);\r\n");
      out.write("    \t\t\t});\r\n");
      out.write("            \t\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            $(\".table thead :checkbox\").click(function(){\r\n");
      out.write("            \tvar checked = this.checked ;\r\n");
      out.write("            \tvar checkboxList = $(\".table tbody :checkbox\");\r\n");
      out.write("            \t$.each(checkboxList,function(i,n){\r\n");
      out.write("            \t\tn.checked = checked ;\r\n");
      out.write("            \t});\r\n");
      out.write("            });\r\n");
      out.write("\t\t\t//传递多个对象的方式\r\n");
      out.write("            $(\"#batchDelete\").click(function(){\r\n");
      out.write("            \tvar checkedList = $(\"table tbody input:checked\");\r\n");
      out.write("            \tif(checkedList.length>0){\r\n");
      out.write("            \t\tlayer.confirm(\"确定要删除吗?\",  {icon: 3, title:'提示'}, function(cindex){\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t\tvar datas = {};\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t\t$.each(checkedList,function(i,n){\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\tdatas[\"datas[\"+i+\"].id\"]=n.value;\r\n");
      out.write("            \t\t\t\tdatas[\"datas[\"+i+\"].name\"]=\"111\";\r\n");
      out.write("            \t\t\t});\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t\t$.ajax({\r\n");
      out.write("            \t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/role/batchDelete.do\",\r\n");
      out.write("            \t\t\t\ttype : \"POST\",\r\n");
      out.write("            \t\t\t\tdata : datas ,\r\n");
      out.write("            \t\t\t\tsuccess : function(result){\r\n");
      out.write("            \t\t\t\t\tif(result.success){\r\n");
      out.write("\t            \t\t\t\t\tlayer.msg(\"删除角色成功!\", {time:1000, icon:6}, function(){\r\n");
      out.write("\t    \t\t\t\t\t\t\t\tqueryPage(1);\r\n");
      out.write("\t    \t\t\t\t\t\t\t});\r\n");
      out.write("            \t\t\t\t\t}else{\r\n");
      out.write("            \t\t\t\t\t\tlayer.msg(\"删除角色失败!\", {time:1000, icon:5});\r\n");
      out.write("            \t\t\t\t\t}\r\n");
      out.write("            \t\t\t\t}\r\n");
      out.write("            \t\t\t});\r\n");
      out.write("        \t\t\t    layer.close(cindex);\r\n");
      out.write("        \t\t\t}, function(cindex){\r\n");
      out.write("        \t\t\t    layer.close(cindex);\r\n");
      out.write("        \t\t\t});\r\n");
      out.write("            \t}\r\n");
      out.write("            });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/script/menu.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/common/menu.jsp(7,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/common/menu.jsp(7,1) '${sessionScope.permissionRoot.children }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.permissionRoot.children }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/common/menu.jsp(7,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("permission");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write('\r');
            out.write('\n');
            out.write('	');
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/jsp/common/menu.jsp(8,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty permission.children}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<li class=\"list-group-item tree-closed\" >\r\n");
          out.write("\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${permission.url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><i class=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${permission.icon}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></i> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${permission.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a> \r\n");
          out.write("\t\t\t</li>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/jsp/common/menu.jsp(13,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty permission.children}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<li class=\"list-group-item tree-closed\">\r\n");
          out.write("\t\t\t\t<span><i class=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${permission.icon}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></i> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${permission.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" <span class=\"badge\" style=\"float:right\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(permission.children)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("    ");
          out.write("</span></span> \r\n");
          out.write("\t\t\t\t<ul style=\"margin-top:10px;display:none;\">\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t</li>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/jsp/common/menu.jsp(17,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/common/menu.jsp(17,5) '${permission.children }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${permission.children }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/common/menu.jsp(17,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("innerPermission");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<li style=\"height:30px;\">\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('/');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${innerPermission.url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><i class=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${innerPermission.icon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></i> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${innerPermission.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a> \r\n");
            out.write("\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
