/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-06-04 07:05:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.permission;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/H:/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Atcrowdfunding-main/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1588300696268L));
    _jspx_dependants.put("/WEB-INF/jsp/common/top.jsp", Long.valueOf(1590029111820L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ztree/zTreeStyle.css\">\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.tree li {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable tbody tr:nth-child(odd){background:#F4F4F4;}\r\n");
      out.write("\ttable tbody td:nth-child(even){color:#C00;}\r\n");
      out.write("\t</style>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <div><a class=\"navbar-brand\" style=\"font-size:32px;\" href=\"user.html\">众筹平台 - 用户维护</a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          \r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("   <li style=\"padding-top:8px;\">\r\n");
      out.write("\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"btn btn-default btn-success dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t  </button>\r\n");
      out.write("\t\t\t\t\t  <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i> 个人设置</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i> 消息</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout.htm\"><i class=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("\t\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("            <li style=\"margin-left:10px;padding-top:8px;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-danger\">\r\n");
      out.write("\t\t\t\t  <span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t     <form class=\"navbar-form navbar-right\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t\t\t<div class=\"tree\">\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/common/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t  <div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t<h3 class=\"panel-title\"><i class=\"glyphicon glyphicon-th\"></i> 许可树</h3>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"treeDemo\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/script/docs.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ztree/jquery.ztree.all-3.5.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery/layer/layer.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/script/menu.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            $(function () {\r\n");
      out.write("\t\t\t    $(\".list-group-item\").click(function(){\r\n");
      out.write("\t\t\t\t    if ( $(this).find(\"ul\") ) {\r\n");
      out.write("\t\t\t\t\t\t$(this).toggleClass(\"tree-closed\");\r\n");
      out.write("\t\t\t\t\t\tif ( $(this).hasClass(\"tree-closed\") ) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).show(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t   loadData();\r\n");
      out.write("\t\t\t   showMenu(); \r\n");
      out.write("            });   \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("         \r\n");
      out.write("    \t\tvar setting = {\r\n");
      out.write("   \t\t\t    view : {\r\n");
      out.write("   \t\t\t    \taddDiyDom: function(treeId, treeNode){\r\n");
      out.write("   \t\t\t\t    \tvar icoObj = $(\"#\" + treeNode.tId + \"_ico\"); // tId = permissionTree_1, $(\"#permissionTree_1_ico\")\r\n");
      out.write("   \t\t\t    \t\tif ( treeNode.icon ) {\r\n");
      out.write("   \t\t\t    \t\t\ticoObj.removeClass(\"button ico_docu ico_open\").addClass(treeNode.icon).css(\"background\",\"\");\r\n");
      out.write("   \t\t\t    \t\t}\r\n");
      out.write("   \t\t\t    \t},\r\n");
      out.write("\t\t\t\t\taddHoverDom: function(treeId, treeNode){   //设置自定义按钮组,在节点后面悬停显示增删改按钮组.\r\n");
      out.write("\t\t\t\t\t\tvar aObj = $(\"#\" + treeNode.tId + \"_a\"); // tId = permissionTree_1, ==> $(\"#permissionTree_1_a\")\r\n");
      out.write("\t\t\t\t\t\taObj.attr(\"href\", \"javascript:;\"); // 取消当前链接事件.\r\n");
      out.write("\t\t\t\t\t\tif (treeNode.editNameFlag || $(\"#btnGroup\"+treeNode.tId).length>0) return;\r\n");
      out.write("\t\t\t\t\t\tvar  s = '<span id=\"btnGroup'+treeNode.tId+'\">';\r\n");
      out.write("\t\t\t\t\t\tif ( treeNode.level == 0 ) { //根节点\r\n");
      out.write("\t\t\t\t\t\t\ts += '<a class=\"btn btn-info dropdown-toggle btn-xs\" style=\"margin-left:10px;padding-top:0px;\" href=\"#\" onclick=\"window.location.href=\\'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/permission/toAdd.htm?id='+treeNode.id+'\\'\" >&nbsp;&nbsp;<i class=\"fa fa-fw fa-plus rbg \"></i></a>';\r\n");
      out.write("\t\t\t\t\t\t} else if ( treeNode.level == 1 ) { //分支节点\r\n");
      out.write("\t\t\t\t\t\t\ts += '<a class=\"btn btn-info dropdown-toggle btn-xs\" style=\"margin-left:10px;padding-top:0px;\"  href=\"#\" onclick=\"window.location.href=\\'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/permission/toUpdate.htm?id='+treeNode.id+'\\'\" title=\"修改权限信息\">&nbsp;&nbsp;<i class=\"fa fa-fw fa-edit rbg \"></i></a>';\r\n");
      out.write("\t\t\t\t\t\t\tif (treeNode.children.length == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\ts += '<a class=\"btn btn-info dropdown-toggle btn-xs\" style=\"margin-left:10px;padding-top:0px;\" href=\"#\" onclick=\"deletePermission('+treeNode.id+','+\"'\"+treeNode.name+\"'\"+')\">&nbsp;&nbsp;<i class=\"fa fa-fw fa-times rbg \"></i></a>';\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\ts += '<a class=\"btn btn-info dropdown-toggle btn-xs\" style=\"margin-left:10px;padding-top:0px;\" href=\"#\" onclick=\"window.location.href=\\'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/permission/toAdd.htm?id='+treeNode.id+'\\'\">&nbsp;&nbsp;<i class=\"fa fa-fw fa-plus rbg \"></i></a>';\r\n");
      out.write("\t\t\t\t\t\t} else if ( treeNode.level == 2 ) { //叶子节点\r\n");
      out.write("\t\t\t\t\t\t\ts += '<a class=\"btn btn-info dropdown-toggle btn-xs\" style=\"margin-left:10px;padding-top:0px;\"  href=\"#\"  onclick=\"window.location.href=\\'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/permission/toUpdate.htm?id='+treeNode.id+'\\'\" title=\"修改权限信息\">&nbsp;&nbsp;<i class=\"fa fa-fw fa-edit rbg \"></i></a>';\r\n");
      out.write("\t\t\t\t\t\t\ts += '<a class=\"btn btn-info dropdown-toggle btn-xs\" style=\"margin-left:10px;padding-top:0px;\" href=\"#\" onclick=\"deletePermission('+treeNode.id+','+\"'\"+treeNode.name+\"'\"+')\">&nbsp;&nbsp;<i class=\"fa fa-fw fa-times rbg \"></i></a>';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\ts += '</span>';\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\taObj.after(s);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tremoveHoverDom: function(treeId, treeNode){\r\n");
      out.write("\t\t\t\t\t\t$(\"#btnGroup\"+treeNode.tId).remove();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("   \t\t\t   }\r\n");
      out.write("    \t\t};\r\n");
      out.write("\r\n");
      out.write("    \t\t/* var zNodes =[\r\n");
      out.write("    \t\t\t{ name:\"父节点1 - 展开\", open:true,\r\n");
      out.write("    \t\t\t\tchildren: [\r\n");
      out.write("    \t\t\t\t\t{ name:\"父节点11 - 折叠\",\r\n");
      out.write("    \t\t\t\t\t\tchildren: [\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点111\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点112\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点113\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点114\"}\r\n");
      out.write("    \t\t\t\t\t\t]},\r\n");
      out.write("    \t\t\t\t\t{ name:\"父节点12 - 折叠\",\r\n");
      out.write("    \t\t\t\t\t\tchildren: [\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点121\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点122\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点123\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点124\"}\r\n");
      out.write("    \t\t\t\t\t\t]},\r\n");
      out.write("    \t\t\t\t\t{ name:\"父节点13 - 没有子节点\", isParent:true}\r\n");
      out.write("    \t\t\t\t]},\r\n");
      out.write("    \t\t\t{ name:\"父节点2 - 折叠\",\r\n");
      out.write("    \t\t\t\tchildren: [\r\n");
      out.write("    \t\t\t\t\t{ name:\"父节点21 - 展开\", open:true,\r\n");
      out.write("    \t\t\t\t\t\tchildren: [\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点211\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点212\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点213\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点214\"}\r\n");
      out.write("    \t\t\t\t\t\t]},\r\n");
      out.write("    \t\t\t\t\t{ name:\"父节点22 - 折叠\",\r\n");
      out.write("    \t\t\t\t\t\tchildren: [\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点221\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点222\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点223\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点224\"}\r\n");
      out.write("    \t\t\t\t\t\t]},\r\n");
      out.write("    \t\t\t\t\t{ name:\"父节点23 - 折叠\",\r\n");
      out.write("    \t\t\t\t\t\tchildren: [\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点231\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点232\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点233\"},\r\n");
      out.write("    \t\t\t\t\t\t\t{ name:\"叶子节点234\"}\r\n");
      out.write("    \t\t\t\t\t\t]}\r\n");
      out.write("    \t\t\t\t]},\r\n");
      out.write("    \t\t\t{ name:\"父节点3 - 没有子节点\", isParent:true}\r\n");
      out.write("\r\n");
      out.write("    \t\t]; */\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("\r\n");
      out.write("    \t\tfunction loadData(){\r\n");
      out.write("    \t\t\t$.ajax({\r\n");
      out.write("    \t\t\t\tdata : null,\r\n");
      out.write("        \t    \turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/permission/loadData.do\",\r\n");
      out.write("        \t    \ttype:\"post\",\r\n");
      out.write("        \t    \tsuccess:function(result){\r\n");
      out.write("        \t    \t\tif(result.success){\r\n");
      out.write("        \t    \t\t\t var zNodes = result.data ;\r\n");
      out.write("        \t    \t\t\t $.fn.zTree.init($(\"#treeDemo\"), setting, zNodes);\r\n");
      out.write("        \t    \t\t}else{\r\n");
      out.write("        \t    \t\t\talert(\"加载数据失败...\");\r\n");
      out.write("        \t    \t\t}\r\n");
      out.write("        \t    \t}\r\n");
      out.write("        \t    \t\r\n");
      out.write("        \t    });\r\n");
      out.write("    \t\t}\r\n");
      out.write("\r\n");
      out.write("    \t\t\r\n");
      out.write("    /* \t\t$(document).ready(function(){\r\n");
      out.write("    \t\t\t$.fn.zTree.init($(\"#treeDemo\"), setting, zNodes);\r\n");
      out.write("    \t\t});  */\r\n");
      out.write("            \r\n");
      out.write("    \t\t  function deletePermission(id,name){\r\n");
      out.write("    \t\t\tlayer.confirm(\"确定要删除[\"+name+\"]许可吗?\",  {icon: 3, title:'提示'}, function(cindex){\r\n");
      out.write("    \t\t\t    layer.close(cindex);\r\n");
      out.write("    \t\t\t    $.ajax({\r\n");
      out.write("    \t\t\t    \ttype : \"POST\",\r\n");
      out.write("            \t    \turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/permission/delete.do\",\r\n");
      out.write("            \t    \tdata : {\r\n");
      out.write("            \t    \t\t\"id\" : id\r\n");
      out.write("            \t    \t},\r\n");
      out.write("\t\t\t\t\t\tbeforeSend : function(){\r\n");
      out.write("                \t\t\treturn true;\r\n");
      out.write("                \t\t},\r\n");
      out.write("            \t    \tsuccess : function(result){\r\n");
      out.write("            \t    \t\tif(result.success){\r\n");
      out.write("            \t    \t\t\tloadData();\r\n");
      out.write("            \t    \t\t}else{\r\n");
      out.write("            \t    \t\t\talert(\"删除许可数据失败...\");\r\n");
      out.write("            \t    \t\t}\r\n");
      out.write("            \t    \t},\r\n");
      out.write("                \t\terror : function(){\r\n");
      out.write("                \t\t\tlayer.msg(\"服务器异常\",{time:1000, icon:5,shift:6});\r\n");
      out.write("                \t\t}            \t    \t\r\n");
      out.write("            \t    });\r\n");
      out.write("    \t\t\t}, function(cindex){\r\n");
      out.write("    \t\t\t    layer.close(cindex);\r\n");
      out.write("    \t\t\t});\r\n");
      out.write("    \t\t}\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
